### ISSUE TITLE
Populate jakarta/kubernetes/meetup.yaml with events we have done

### ISSUE THREAD

**Issue by girikuncoro** [cloudnative-id/meetups#16]
`meetup.yaml` should include meetup list that we have done, write some hack scripts if needed to fetch data through Meetup API.

**Comment by irvifa** [comment]
Is this only for cloudnative or all meetup in jakarta including kubernetes one? @girikuncoro

**Comment by girikuncoro** [comment]
this is only for kubernetes jakarta, migrating to new toolings (when done) and populate meetup.yaml is each meetup owners' responsibility
