### ISSUE TITLE
Populate speaker info by referring to speakers.yaml

### ISSUE THREAD

**Issue by girikuncoro** [cloudnative-id/meetups#18]
**Is your feature request related to a problem? Please describe.**
Currently in each meetup README.md, only speaker id is included (example: `girikuncoro`). We need to populate more info and link them to github handle (or twitter?).

**Describe the solution you'd like**
Instead of outputting `girikuncoro`, we need to do: `Giri Kuncoro, [@girikuncoro](github link), CNCF Ambassador, [Gojek](company link)`

**Comment by girikuncoro** [comment]
just to be clear: this needs to be implemented in `generator` tool

**Comment by imrenagi** [comment]
Ini gw yang ambil deh ya @girikuncoro

**Comment by girikuncoro** [comment]
sure
