### ISSUE TITLE
Kubernetes Jakarta at Nodeflux #13

### ISSUE THREAD

**Issue by eufat** [cloudnative-id/meetups#29]
### 2-4 weeks before the event
- [x] Decide on date
- [x] Find speaker 1: Dedy Efendi
- [x] Find speaker 2: Alvin Prayuda
- [x] Find venue sponsor: Nodeflux
- [x] Get speakers to fill up [speaker form](https://docs.google.com/forms/d/e/1FAIpQLSewmKuIlk37uye_sgyqed9k2gSPhVf4yy9KGZskA1NjAXq6cw/viewform)

### 1 week before the event
- [x] Create meetup.com event page (refer to TODO)
- [x] Add the sponsor logo to meetup.com event sponsor section, ordered from the most recent one
- [x] Create bit.ly link to the meetup.com page
- [x] Create event poster using our [generator tool](https://github.com/cloudnative-id/artwork/tree/master/poster/generator) or [canva](https://www.canva.com/)
- [x] Upload poster into meetup.com page
- [x] Get the poster and meetup.com page reviewed by speakers and sponsor
- [x] Announce meetup.com event page
- [x] Announce meetup event in Telegram groups ([Kubernetes Indonesia](https://t.me/kubernetesindonesia), [Cloud Native Indonesia](https://t.me/microserviceid), [Docker Indonesia](https://t.me/dockeridn), [IDDevops](https://t.me/IDDevOps))
- [x] Prepare community slide for event (refer to TODO)
- [x] Coordinate with sponsor venue for event rundown and host
- [x] Optional: Order foods/snacks for event (usually provided by sponsor)
- [ ] Optional: Order merchandise for speakers

### 3 days before the event
- [x] Prepare slides for welcoming and community update (refer to TODO)
- [x] Print [Check In QR Code](./checkin-qr-code.png) and [Survey QR Code](./survey-qr-code.png) and bring them to the event venue

### The meetup event day
- [x] Remind speakers to come ontime
- [x] Optional: Bring swags for the meetup
- [x] Arrive 1 hour before the event starts
- [x] Ask the participants to checkin by using this [Check In QR Code](./checkin-qr-code.png)
- [x] Optional: Prepare live streaming or recording tools (use Zoom or refer to [recording meetup event](https://github.com/cloudnative-id/meetups/RECORDING_MEETUP_EVENT.md))
- [x] Host the event (refer to TODO)
- [x] Ask the participants to fill the survey form by using this [Survey QR Code](./survey-qr-code.png)
- [x] Take pictures with speakers and participants

### 3 days after the event
- [x] Get slides from speakers
- [x] Upload slides from speakers to Github (refer to TODO)
- [x] Upload selected pictures to meetup.com page
- [ ] Upload pictures to community drive or Google photos (refer to TODO)
- [x] Optional: { if recorded } Upload videos to Youtube (refer to TODO)
- [ ] Send out thank you to Telegram groups (refer to TODO)
- [ ] Send out thank you to sponsors (refer to TODO)
- [x] Optional: { if needed } Reimburse your venue/food cost to @girikuncoro

**Comment by girikuncoro** [comment]
Speaker 1 (intro to kubernetes): reached out to Dedy Efendi as he stated interest to give talks in the group, waiting for reply

Update: Dedy has confirmed availability on 30 jan

**Comment by eufat** [comment]
Speaker 2 (kubernetes for AI, kubeflow): asked Alvin Prayuda as he prepared for title, confirmed availability on 30 january.

**Comment by eufat** [comment]
Jadwal Pelaksanaan Acara:
Event Title: Meetup Jakarta Kubernetes #13 X Nodeflux TechTalk
Venue: Nodeflux (Lapangan Basket)
Date: Kamis, 30 Januari 2020

Pembicara:
Speaker 1: Dedy Efendi, Site Reliability Engineer at DANA
Speaker 2: Alvin Prayuda, Research Group Lead at Nodeflux

Topik:
Topik 1: Intro to Kubernetes
Topik 2: A scalable training approach using Kubeflow

Rundown:
18:30 - 19:09    Registration
19:09 - 19:25    Welcome Sponsor & Community Update
19:25 - 19:55    1st Session
19:55 - 20:25    2nd Session
20:25 - 20:40    Q&A Panel
20:40 - 21:00    Networking Session

**Comment by eufat** [comment]
![jk8s-jan20](https://user-images.githubusercontent.com/3710666/73072760-6a00e600-3ee8-11ea-9ee3-44e26a334fa9.png)

**Comment by eufat** [comment]
Youtube Live Streaming: https://www.youtube.com/watch?v=0FqofHUk7hY
