### ISSUE TITLE
Kubernetes and Cloud Native Jakarta #16

### ISSUE THREAD

**Issue by zufardhiyaulhaq** [cloudnative-id/meetups#41]
## Scheduled to happen: 
2020-06-30

### 2-4 weeks before the event
- [x] Decide on date
- [x] Find speaker 1: Zainal Abidin
- [x] Find speaker 2: Srinivasa Vasu
- [x] Find venue sponsor: Youtube
- [x] Get speakers to fill up [speaker form](https://docs.google.com/forms/d/e/1FAIpQLSewmKuIlk37uye_sgyqed9k2gSPhVf4yy9KGZskA1NjAXq6cw/viewform)

### 1 week before the event
- [x] Create meetup.com event page (refer to [this template](https://github.com/cloudnative-id/meetups/blob/master/docs/MEETUP_DESCRIPTION.md))
- [ ] Add the sponsor logo to meetup.com event sponsor section, ordered from the most recent one
- [x] Create bit.ly link to the meetup.com page
- [x] Create event poster using our [generator tool](https://github.com/cloudnative-id/artwork/tree/master/poster/generator) or [canva](https://www.canva.com/)
- [x] Upload poster into meetup.com page
- [x] Get the poster and meetup.com page reviewed by speakers and sponsor
- [x] Announce meetup.com event page
- [x] Announce meetup event in Telegram groups ([Kubernetes Indonesia](https://t.me/kubernetesindonesia), [Cloud Native Indonesia](https://t.me/microserviceid), [Docker Indonesia](https://t.me/dockeridn), [IDDevops](https://t.me/IDDevOps))
- [x] Prepare community slide for event (refer to TODO)
- [ ] Coordinate with sponsor venue for event rundown and host
- [ ] Optional: Order foods/snacks for event (usually provided by sponsor)
- [ ] Optional: Order merchandise for speakers

### 3 days before the event
- [x] Prepare slides for welcoming and community update (refer to TODO)
- [ ] Print [Check In QR Code](./checkin-qr-code.png) and [Survey QR Code](./survey-qr-code.png) and bring them to the event venue

### The meetup event day
- [x] Remind speakers to come ontime
- [ ] Optional: Bring swags for the meetup
- [x] Arrive 1 hour before the event starts
- [ ] Ask the participants to checkin by using this [Check In QR Code](./checkin-qr-code.png)
- [x] Optional: Prepare live streaming or recording tools (use Zoom or refer to [recording meetup event](https://github.com/cloudnative-id/meetups/RECORDING_MEETUP_EVENT.md))
- [x] Host the event (refer to TODO)
- [ ] Ask the participants to fill the survey form by using this [Survey QR Code](./survey-qr-code.png)
- [ ] Take pictures with speakers and participants

### 3 days after the event
- [x] Get slides from speakers
- [x] Upload slides (in the form of PDF so that it will be persisted) from speakers to Github (refer to TODO). You can do it in the "slides" folder in your city's folder. 
- [ ] Upload selected pictures to meetup.com page
- [ ] Upload pictures to community drive or Google photos (refer to TODO)
- [x] Optional: { if recorded } Upload videos to Youtube (refer to TODO)
- [ ] Send out thank you to Telegram groups (refer to TODO)
- [ ] Send out thank you to sponsors (refer to TODO)
- [ ] Optional: { if needed } Reimburse your venue/food cost to @girikuncoro

**Comment by irvifa** [comment]
By the way is this fixed already @zufardhiyaulhaq ?

**Comment by zufardhiyaulhaq** [comment]
@irvifa fix the title

**Comment by girikuncoro** [comment]
community slide https://docs.google.com/presentation/d/1E5WEjpHNtmV0yC6asoWxBtl-6mjenOvBLAjhDC8turM

**Comment by girikuncoro** [comment]
some of the todo lists might need to be adjusted since we are now mostly online

**Comment by zufardhiyaulhaq** [comment]
should we expected to all complete todo lists/ create a new todo lists since we will be scheduling online meetup until end of the year?

**Comment by zufardhiyaulhaq** [comment]
@girikuncoro can you send Srinivasa Vasu slide here?

**Comment by girikuncoro** [comment]
@zufardhiyaulhaq here you go https://github.com/cloudnative-id/meetups/blob/master/jakarta/kubernetes/slides/16-intro-cluster-api.pdf

**Comment by girikuncoro** [comment]
> should we expected to all complete todo lists/ create a new todo lists since we will be scheduling online meetup until end of the year?

I think you are right, we should modify the checklist for online meetups @zufardhiyaulhaq lets talk about it tonight

**Comment by irvifa** [comment]
Having a spreadsheet will be really helpful. At the very least there should be a list choices of the venue and stuff. I suggest we postpone the date until 2121 since CloudNativeCon and KubeCon Boston also virtual event. 

Any CNCF events this year is practically virtual events until at least spring 2121.
