### ISSUE TITLE
Kubernetes and Cloud Native Jakarta July Talk

### ISSUE THREAD

**Issue by irvifa** [cloudnative-id/meetups#44]
Please use the form below if you would like to speak, sponsor, or host an upcoming Cloud Native Indonesia Meetup.

SPEAKERS - We like short talks! We will have a long speaker queue and need to do at least two talks per meetup. More than 30 minutes will not be accepted.

If you need inspiration, you can find many awesome Kubernetes talks below.
Kubecon playlist:

- https://bit.ly/2R60t3b
- https://bit.ly/2LcQABQ
- https://bit.ly/2BogzOi

TGIK: 
- https://bit.ly/2POYjIs

## I am a: *

- [ ] Venue/Host
- [x] Speaker - the audiences are engineers, please avoid any marketing oriented talks

## Which cloud native community you are referring to when filling this form? *

- [x] Jakarta Kubernetes
- [ ] Cloud Native Jakarta User Group
- [ ] Kubernetes and Cloud Native Bandung
- [ ] Kubernetes and Cloud Native Yogyakarta

## Fullname *
Giovan Isa Musthofa
Irvi Aini

## Organisation/Company Name *
University of Indonesia
Kubernetes

## Current Position/Role *
Undergraduate Student
Engineer

## Speakers: Have you given this talk before? Do you have link to slides, videos, etc.? *
Yes
- https://www.youtube.com/watch?v=Uis_o_8Ui1I
- https://github.com/irvifa/meetups-slides

## Speakers: Please provide your talk abstract and time needed *
Storage in K8s. 30 minutes.

## Speakers: Please provide your short bio. *

Giovan is an undergraduate student majoring in Computer Science who is passionate about helping others on new things and the things he already excel with. He already familiar with git, Python, C#, Unity3D, Linux, and Docker. He is working on his skills and knowledge in FOSS, DevOps, Information Security, and CTF. He also contributed in [Rook](https://rook.io/) during his time in Google Summer of Code. 

Irvi is a Software Engineer, previously working in her team's migration to Kubernetes. She was working as part of global committee for Helm Summit 2019 in Amsterdam, program committee in GHC 2020. She is co-owners of of SIG Docs for Indonesian language localization, part of Kubernetes Release Team 1.17 and 1.18, and shadow of chairs of SIG Docs. Exploring language parsing with Rust and R, reading, and traveling. She also a contributor of several open source projects like Kubernetes, Planout and Ax (Facebook), Google Cloud Platform Community and Google API (Google), Keras.

## Your Photo for Poster *
Note - Please upload photo with 1:1 ratio.

**Comment by giovanism** [comment]
Test foto yang udah publik.
![foto](https://www.cncf.io/wp-content/uploads/2019/08/temp-225x300.jpg)

**Comment by irvifa** [comment]
<img width="438" alt="irvi" src="https://user-images.githubusercontent.com/7439590/87307528-fd37e180-c543-11ea-9b61-c1bc9c910651.png">
