### ISSUE TITLE
Kubernetes and Cloud Native Bandung #4

### ISSUE THREAD

**Issue by joshuabezaleel** [cloudnative-id/meetups#5]
### 2-4 weeks before the event
- [x] Decide on date
- [x] Find speaker 1 (refer to TODO)
- [x] Find speaker 2
- [x] Find venue sponsor (refer to TODO)
- [x] Get speakers to fill up speaker form (refer to TODO)

### 1 week before the event
- [x] Create meetup.com event page (refer to TODO)
- [x] Add the sponsor logo to meetup.com event sponsor section, ordered from the most recent one
- [x] Create bit.ly link to the meetup.com page
- [x] Create event poster using our [generator tool](https://github.com/cloudnative-id/artwork/tree/master/poster/generator) or [canva](https://www.canva.com/)
- [x] Upload poster into meetup.com page
- [x] Announce meetup.com event page
- [x] Announce meetup event in Telegram groups ([Kubernetes Indonesia](https://t.me/kubernetesindonesia), [Cloud Native Indonesia](https://t.me/microserviceid), [Docker Indonesia](https://t.me/dockeridn), [IDDevops](https://t.me/IDDevOps))
- [x] Prepare community slide for event (refer to TODO)
- [x] Coordinate with sponsor venue for event rundown and host
- [x] Optional: Order foods/snacks for event (usually provided by sponsor)
- [x] Optional: Order merchandise for speakers

### The meetup event day
- [x] Remind speakers to come ontime
- [x] Arrive 1 hour before the event starts
- [x] Optional: Prepare live streaming or recording tools (use Zoom or refer to [recording meetup event](RECORDING_MEETUP_EVENT.md))
- [x] Host the event (refer to TODO)
- [x] Take pictures with speakers and participants

### 3 days after the event
- [x] Get slides from speakers
- [x] Upload slides from speakers to Github (refer to TODO)
- [x] Upload selected pictures to meetup.com page
- [x] Upload pictures to community drive or Google photos (refer to TODO)
- [x] Optional: { if recorded } Upload videos to Youtube (refer to TODO)
- [x] Send out thank you to Telegram groups (refer to TODO)
- [x] Send out thank you to sponsors (refer to TODO)
- [x] Optional: { if needed } Reimburse your venue/food cost to @girikuncoro

**Comment by joshuabezaleel** [comment]
Venue sponsor: Jabar Digital Service (PIC: Aditya Satrya), 
Theme: TBD

Speaker 1: TBD
Speaker 2: TBD

**Comment by zufardhiyaulhaq** [comment]
Update:
- Speaker 1: Aditya Satrya (Jabar Digital Service)
- Speaker 2: Imre Nagi

**Comment by zufardhiyaulhaq** [comment]
Update:

- Meetup page created, https://www.meetup.com/Kubernetes-and-Cloud-Native-Bandung/events/267202957/

**Comment by zufardhiyaulhaq** [comment]
Update Slide:
- Community Slide https://docs.google.com/presentation/d/1zcRRw_rWuRbcfAv-SowzZI7Cs6yQ8-q7qy_Of42KFnY/edit#slide=id.g4c35bb3ebd_2_71
- Talk 1 https://docs.google.com/presentation/d/18pMWvKM3m_MCtX_095za4ogG2Oog-c8wfMxkTWImYFc/edit?usp=sharing
- Talk 2 https://docs.google.com/presentation/d/1pUgTksN6qn3oDkSp8tmQB5QGzCl1T7R_Uphwulk6daI/edit?usp=sharing
- Video: https://www.youtube.com/watch?v=u0Miv0Et_s8&feature=youtu.be

**Comment by girikuncoro** [comment]
@zufardhiyaulhaq diupload seperti biasa saja dulu di repo bandung, sambil nunggu meetops nya jadi yang pake yamls
